spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/second_hand_trade?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root # 替换为你的数据库用户名
    password: root # 替换为你的数据库密码
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080 # 项目端口

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml # 若用XML写SQL需配置
  type-aliases-package: com.secondhandtradingsystem.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志

# JWT 配置（适配JwtUtil）
trade:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: abcdefghijklmnopqrstuvwxyz1234567890abcdef
    # 设置jwt过期时间
    admin-ttl: 2592000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: abcdefghijklmnopqrstuvwxyz1234567890abcdef
    user-ttl: 2592000000
    user-token-name: token

minio:
  endpoint: http://192.168.43.20:19966
  accessKey: admin
  secretKey: myj040520
  bucketName: my-project